---
# tasks file for haproxy
- name: Install haproxy
  apt: name=haproxy state=present update_cache=yes

- name: Configure haproxy
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg mode=0644
  notify: restart haproxy

- name: "Add hostnames to /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    line: "{{ item.ip }} {{ item.hostname }}"
    state: present
  with_items: "{{ galeraservers }}"
  notify: restart haproxy

- name: Install Python MySQL library
  apt: name=python-mysqldb state=present update_cache=yes

- name: Add haproxy mysql user
  mysql_user:
    name: "{{ haproxy_user }}"
    password: "{{ haproxy_pass }}"
    priv: "*.*:ALL"
    state: present
    host: "{{ haproxy_host }}"
