---
# tasks file for apache

- name: Install Apache 2
  apt: name=apache2 state=present update_cache=yes

- name: Install Apache 2 modules and extensions
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - apache2-doc
    - apache2-utils
    - libapache2-mod-php
    - libapache2-mod-fcgid
    - apache2-suexec-pristine
    - libapache2-mod-python
    - libapache2-mod-fastcgi
  notify: restart apache

- name: Enable apache modules
  apache2_module: name={{ item }} state=present
  with_items:
    - suexec
    - rewrite
    - ssl
    - actions
    - include
    - cgi
    - fastcgi
  notify: restart apache

- name: Enable more apache modules
  apache2_module: name={{ item }} state=present
  with_items:
    - dav_fs
    - dav
    - auth_digest
    - headers
  notify: restart apache

# Handle virtual hosts
- name: Create vhosts directories
  file:
    path: /var/www/{{ item.server_name }}/public_html
    recurse: yes
    state: directory
  with_items: "{{ vhosts }}"

- name: Create apache vhosts config files
  template: src=vhost.dev.conf.j2 dest="/etc/apache2/sites-available/{{ item.server_name }}.conf" owner=root group=root mode=0644
  with_items: "{{ vhosts }}"

- name: Enable vhosts
  file:
    src: /etc/apache2/sites-available/{{ item.server_name }}.conf
    dest: /etc/apache2/sites-enabled/{{ item.server_name }}.conf
    state: link
  with_items: "{{ vhosts_enabled }}"
  notify: restart apache

- name: Add index.html files to vhosts docroots
  template:
    src: index.html.j2
    dest: "/var/www/{{ item.server_name }}/public_html/index.html"
  with_items: "{{ vhosts }}"

- name: Disable default vhost
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart apache
  when: disable_default_vhost
