---
# tasks file for apt

- name: Updating APT package manager repositories cache
  become: true
  apt:
    update_cache: yes

- name: Upgrading installed packages
  become: true
  apt:
    upgrade: safe

- name: Reboot
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for Raspberry PI to come back
  local_action: wait_for host={{ item }} port=22 state=started delay=10
  become: false
  with_items: "{{ play_hosts }}"
