---
# tasks file for nginx
- name: Install tools
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - python-httplib2

- name: install nginx
  apt: name=nginx state=present update_cache=yes

- name: Ensure nginx is running
  service: name=nginx state=started enabled=yes

- name: Configure nginx sites
  template: src=nginx.default.conf.j2 dest=/etc/nginx/sites-available/default mode=0644
  notify: restart nginx

- name: Get active sites
  shell: ls -1 /etc/nginx/sites-enabled
  register: active

- name: Deactivate all nginx sites
  file:
    path: /etc/nginx/sites-enabled/
    state: absent

- name: Recreate sites-enabled directory
  file:
    path: /etc/nginx/sites-enabled/
    state: directory

- name: Activate default nginx site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: restart nginx

- name: "Add hostnames to /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    line: "{{ item.ip }} {{ item.hostname }}"
    state: present
  with_items: "{{ galeraservers }}"
  notify: restart nginx

- name: Modify nginx config
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '^        # server_names_hash_bucket_size 64;'
    line: '        server_names_hash_bucket_size 64;'
  notify: restart nginx
