---
# tasks file for nginx
- name: install tools
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - python-httplib2

- name: install nginx
  apt: name=nginx state=present update_cache=yes

- name: ensure nginx is running
  service: name=nginx state=started enabled=yes

- name: configure nginx site
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{ item.value.server_name }} mode=0644
  with_dict: "{{ sites }}"
  notify: restart nginx

- name: get active sites
  shell: ls -1 /etc/nginx/sites-enabled
  register: active

- name: deactivate default nginx site
  file: path=/etc/nginx/sites-enabled/{{ item }} state=absent
  with_items: "{{ active.stdout_lines }}"
  when: item not in sites
  notify: restart nginx

- name: activate nginx sites
  file:
    src: /etc/nginx/sites-available/{{ item.value.server_name }}
    dest: /etc/nginx/sites-enabled/{{ item.value.server_name }}
    state: link
  with_dict: "{{ sites }}"
  notify: restart nginx

- name: "Add hostnames to /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    line: "{{ item.ip }} {{ item.hostname }}"
    state: present
  with_items: "{{ webservers }}"
  notify: restart nginx

- name: Modify nginx config
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '^        # server_names_hash_bucket_size 64;'
    line: '        server_names_hash_bucket_size 64;'
  notify: restart nginx
