---
# tasks file for php


#php7.0-curl php7.0-intl php7.0-pspell php7.0-recode php7.0-sqlite3 php7.0-tidy php7.0-xmlrpc php7.0-xsl memcached php-memcache php-imagick php-gettext php7.0-zip php7.0-mbstring;
# php-pear php7.0-mcrypt mcrypt  imagemagick libruby php7.0-cli php7.0-cgi php7.0 php7.0-common php7.0-gd php7.0-mysql php7.0-imap

# PHP-FPM support
#sudo apt-get -y install php7.0-fpm;

# enable the modules and restart apache
#sudo a2enmod actions fastcgi alias;
#sudo service apache2 restart;
