---
# tasks file for php

- name: Adding PHP 7.1 repo to apt
  apt_repository:
    repo: 'ppa:ondrej/php'
    update_cache: yes

- name: Install PHP 5.6
  apt: name=php5.6 state=present update_cache=yes
  notify: restart apache

- name: Install PHP 5.6 libraries
  apt: name={{ item }} state=present update_cache=yes
  with_items: "{{ php56libraries }}"
  notify: restart apache

- name: Install PHP 7.0
  apt: name=php7.0 state=present update_cache=yes
  notify: restart apache

- name: Install PHP 7.0 libraries
  apt: name={{ item }} state=present update_cache=yes
  with_items: "{{ php70libraries }}"
  notify: restart apache

- name: Install PHP 7.1
  apt: name=php7.1 state=present update_cache=yes
  notify: restart apache

- name: Install PHP 7.1 libraries
  apt: name={{ item }} state=present update_cache=yes
  with_items: "{{ php71libraries }}"
  notify: restart apache

- name: Install PHP 7.2
  apt: name=php7.2 state=present update_cache=yes
  notify: restart apache

- name: Install PHP 7.2 libraries
  apt: name={{ item }} state=present update_cache=yes
  with_items: "{{ php72libraries }}"
  notify: restart apache

# - name: Enable apache modules
#   apache2_module: name={{ item }} state=present
#   with_items:
#     - suexec
#     - rewrite
#     - ssl
#     - actions
#     - include
#     - cgi
#   notify: restart apache

 


# enable the modules and restart apache
#sudo a2enmod actions fastcgi alias;
#sudo service apache2 restart;
