---
# defaults file for nginxlbweb
webservers:
  - ip: "104.131.133.21"
    hostname: "do.webserver1"
  - ip: "104.131.133.39"
    hostname: "do.webserver2"

sites:
  example1:
    server_name: "example1.dev"
    server_alias: "www.example1.dev"
    frontend: 80
    backend: 80
    loadbalance_method: "least_conn;" #options: (empty-string) = round-robin, least_conn;, ip_hash;
  example2:
    server_name: "example2.dev"
    server_alias: "www.example2.dev"
    frontend: 80
    backend: 80
    loadbalance_method: "least_conn;" #options: (empty-string) = round-robin, least_conn;, ip_hash;
  example3:
    server_name: "example3.dev"
    server_alias: "www.example3.dev"
    frontend: 80
    backend: 80
    loadbalance_method: "least_conn;" #options: (empty-string) = round-robin, least_conn;, ip_hash;
